server:
  port: 8081
  servlet:
    context-path: "/"



spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test1?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=false
    username: root
    password: root
  thymeleaf:
    cache: false
  application:
    name: user-service




logging:
  level:
    com.litty.cloud: debug
    org.springframework: info


mybatis:
  type-aliases-package: com.litty.cloud.entity
  configuration:
    map-underscore-to-camel-case: true
  #mapper-locations: mappers/*Mapper.xml



eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      #defaultZone: http://127.0.0.1:10086/eureka/   #单机版
      defaultZone: http://127.0.0.1:10086/eureka/,http://127.0.0.1:10087/eureka/,http://127.0.0.1:10088/eureka/    #集群版
    register-with-eureka: true # 向EurekaServer发起一个Rest请求，并携带自己的元数据信息，Eureka Server会把这些信息保存到一个双层Map结构中。第一层Map的Key就是服务名称，第二层Map的key是服务的实例id。
  instance:
    # 默认格式是：`${hostname} + ${spring.application.name} + ${server.port}`
    #  - instance-id是区分同一服务的不同实例的唯一标准，因此不能重复。
    instance-id: provide-user8081  #显示项目别名
    prefer-ip-address: true     #访问路径可以显示IP地址
    #也就是说，默认情况下每个30秒服务会向注册中心发送一次心跳，证明自己还活着。如果超过90秒没有发送心跳，EurekaServer就会认为该服务宕机，会从服务列表中移除，这两个值在生产环境不要修改，默认即可。
    lease-expiration-duration-in-seconds: 90 #服务失效时间，默认值90秒
    lease-renewal-interval-in-seconds: 30 #服务续约(renew)的间隔，默认为30秒
    #ip-address: 127.0.0.1






info:
  app.name: litty-appcloud
  company.name: www.litty.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$








