

server:
  port: 9527



spring:
  application:
    name: api-gateway



#zuul:
  #routes:
    #user-service:
      #id: user-service8081-id # 这里是路由id，随意写
      #serviceId: user-service8081-serviceid
      #path: /user-service/** # 这里是映射路径
      #url: http://127.0.0.1:8081 # 映射路径对应的实际url地址











eureka:
  client:
    service-url:
      #defaultZone: http://127.0.0.1:10086/eureka/   #单机版
      defaultZone: http://127.0.0.1:10086/eureka/,http://127.0.0.1:10087/eureka/,http://127.0.0.1:10088/eureka/    #集群版
    registry-fetch-interval-seconds: 30 # 获取服务列表的周期
  instance:
    instance-id: gateway-9527
    #ip-address: 127.0.0.1
    prefer-ip-address: true





#zuul:
  #routes:
    #user-service:
      #serviceId: user-service # 指定服务名称
      #path: /myservice/** # 这里是映射路径





ribbon:
  ConnectTimeout: 250 # 连接超时时间(ms)
  ReadTimeout: 2000 # 通信超时时间(ms)
  OkToRetryOnAllOperations: true # 是否对所有操作重试
  MaxAutoRetriesNextServer: 1 # 同一服务不同实例的重试次数
  MaxAutoRetries: 1 # 同一实例的重试次数


# 默认情况下，一切服务的映射路径就是服务名本身。
#  - 例如服务名为：`user-service`，则默认的映射路径就是：`/user-service/**`
zuul:
  routes:
    user-service: /myservice/** # 这里是映射路径
    user-consume: /myconsume/**
  prefix: /api # 配置路由前缀
  retryable: true
  #ignored-services:
  #  - user-consume


hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMillisecond: 8000 # 熔断超时时长：6000ms







